### ISSUE TITLE
Switch to Python 3

### ISSUE THREAD

**Issue by mubaris** [AlthafHussainK/helloworld_python#1]
Python 2 is dead. Start learning Python 3.

**Comment by AlthafHussainK** [comment]
@mubaris Thanks, I'll be switching to Python 3 :smile:

**Comment by mubaris** [comment]
Python 2 is DEAD

**Comment by AlthafHussainK** [comment]
@mubaris , It was quite a little bit confusing as I am learning in python 2. So I decided to shift to python 3 after completing my course.
